In [1]:
import numpy as np

In [3]:
arr1 = np.array([12,65,990,132])

In [5]:
arr1

array([ 12,  65, 990, 132])

In [9]:
arr1/100

array([0.12, 0.65, 9.9 , 1.32])

In [11]:
arr1/200

array([0.06 , 0.325, 4.95 , 0.66 ])

In [13]:
arr1/1

array([ 12.,  65., 990., 132.])

In [15]:
arr1.shape

(4,)

In [17]:
type(arr1)

numpy.ndarray

In [31]:
two_dim = np.array([[129, 76, 0], [90, 100, 120]])

In [35]:
two_dim

array([[ 12.9,  76. ,   0. ],
       [ 90. , 100. , 120. ]])

In [37]:
type(two_dim)

numpy.ndarray

In [41]:
two_dim.shape

(2, 3)

In [45]:
name = np.array([["Nimish","Omkar","Sagar"],["Umesh","Radha","Tina"]])

In [53]:
#Three Dimensional Array 

In [57]:
three_dim = np.array([["Reema","Jaswant","Kavita"],["Salman","Pamela","Oliver"],["Hemant","yash","Nandani"]])

In [59]:
three_dim

array([['Reema', 'Jaswant', 'Kavita'],
       ['Salman', 'Pamela', 'Oliver'],
       ['Hemant', 'yash', 'Nandani']], dtype='<U7')

In [61]:
three_dim.shape

(3, 3)

In [70]:
import pandas as pd

In [72]:
students = {'rollno':[10,11,12,13,14], 'name':['shivam', 'nimish', 'amit', 'nikita', 'sapna'], 'marks':[63, 75, 78, 84,86]}

In [74]:
students

{'rollno': [10, 11, 12, 13, 14],
 'name': ['shivam', 'nimish', 'amit', 'nikita', 'sapna'],
 'marks': [63, 75, 78, 84, 86]}

In [76]:
d1 = pd.DataFrame(students)

In [78]:
d1

rollno    name  marks
0      10  shivam     63
1      11  nimish     75
2      12    amit     78
3      13  nikita     84
4      14   sapna     86

In [99]:
employee_name = {
    "employeeID" : [1,2,3,4,5],
    "Name": ["Nimish Mothghare","Sanika Kamble","Damini Sharma","Pamela anderson","Ishita Rane"],
    "Salary": [1200,4300,7600,1200,7800]
}

In [101]:
employee = pd.DataFrame(employee_name)


In [103]:
employee

employeeID              Name  Salary
0           1  Nimish Mothghare    1200
1           2     Sanika Kamble    4300
2           3     Damini Sharma    7600
3           4   Pamela anderson    1200
4           5       Ishita Rane    7800

In [105]:
employee["Department"] = ["HR","Operation","Mobile Department","Digital Marketing","Testing Department"]

In [107]:
employee

employeeID              Name  Salary          Department
0           1  Nimish Mothghare    1200                  HR
1           2     Sanika Kamble    4300           Operation
2           3     Damini Sharma    7600   Mobile Department
3           4   Pamela anderson    1200   Digital Marketing
4           5       Ishita Rane    7800  Testing Department

In [109]:
new_employee = {"employeeID" : 6,"Name" : "Fatima Shaikh","Salary": 7900,"Department": "Sales"}

In [115]:
employee = pd.concat([employee, pd.DataFrame([new_employee])],ignore_index = True)

In [117]:
employee

employeeID              Name  Salary          Department
0           1  Nimish Mothghare    1200                  HR
1           2     Sanika Kamble    4300           Operation
2           3     Damini Sharma    7600   Mobile Department
3           4   Pamela anderson    1200   Digital Marketing
4           5       Ishita Rane    7800  Testing Department
5           6     Fatima Shaikh    7900               Sales

In [119]:
employee.to_csv("employee_data.csv", index = False)

In [121]:
print("CSV file saved successfully!")

CSV file saved successfully!


In [125]:
player = pd.read_csv("teams.csv")

In [127]:
player

id        name code                                         image_path  \
0      1    Pakistan  PAK  https://cdn.sportmonks.com/images/cricket/team...   
1     10       India  IND  https://cdn.sportmonks.com/images/cricket/team...   
2     36   Australia  AUS  https://cdn.sportmonks.com/images/cricket/team...   
3     37  Bangladesh  BGD  https://cdn.sportmonks.com/images/cricket/team...   
4     38     England  ENG  https://cdn.sportmonks.com/images/cricket/team...   
..   ...         ...  ...                                                ...   
73  2156     Croatia  HRV                         https://cdn.sportmonks.com   
74  2183   Indonesia  ISN  https://cdn.sportmonks.com/images/cricket/team...   
75  2186       Japan  JPN  https://cdn.sportmonks.com/images/cricket/team...   
76  2252      Rwanda  RWA  https://cdn.sportmonks.com/images/cricket/team...   
77  2255    Tanzania  TZA  https://cdn.sportmonks.com/images/cricket/team...   

    country_id  national_team                   updated_at  
0       190324           True  2018-11-29T11:47:20.000000Z  
1       190324           True  2018-11-29T11:47:20.000000Z  
2       190324           True  2018-11-29T11:47:20.000000Z  
3       190324           True  2018-11-29T11:47:20.000000Z  
4       190324           True  2019-01-29T11:07:04.000000Z  
..         ...            ...                          ...  
73      190324          False  2022-07-24T12:50:38.000000Z  
74      190324          False  2022-08-04T13:54:57.000000Z  
75      190324          False  2022-08-04T13:55:57.000000Z  
76      190324          False  2022-10-29T19:53:57.000000Z  
77      190324          False  2022-10-29T19:55:07.000000Z  

[78 rows x 7 columns]

In [129]:
print(player.to_string())

      id                      name code                                                   image_path  country_id  national_team                   updated_at
0      1                  Pakistan  PAK      https://cdn.sportmonks.com/images/cricket/teams/1/1.png      190324           True  2018-11-29T11:47:20.000000Z
1     10                     India  IND    https://cdn.sportmonks.com/images/cricket/teams/10/10.png      190324           True  2018-11-29T11:47:20.000000Z
2     36                 Australia  AUS     https://cdn.sportmonks.com/images/cricket/teams/4/36.png      190324           True  2018-11-29T11:47:20.000000Z
3     37                Bangladesh  BGD     https://cdn.sportmonks.com/images/cricket/teams/5/37.png      190324           True  2018-11-29T11:47:20.000000Z
4     38                   England  ENG     https://cdn.sportmonks.com/images/cricket/teams/6/38.png      190324           True  2019-01-29T11:07:04.000000Z
5     39                 Sri Lanka  LKA     https://cdn.sp

In [131]:
player.loc[0,"name"] = "Ghana"

In [133]:
player.to_csv("teams.csv", index=False)

In [135]:
print(player.to_string())

      id                      name code                                                   image_path  country_id  national_team                   updated_at
0      1                     Ghana  PAK      https://cdn.sportmonks.com/images/cricket/teams/1/1.png      190324           True  2018-11-29T11:47:20.000000Z
1     10                     India  IND    https://cdn.sportmonks.com/images/cricket/teams/10/10.png      190324           True  2018-11-29T11:47:20.000000Z
2     36                 Australia  AUS     https://cdn.sportmonks.com/images/cricket/teams/4/36.png      190324           True  2018-11-29T11:47:20.000000Z
3     37                Bangladesh  BGD     https://cdn.sportmonks.com/images/cricket/teams/5/37.png      190324           True  2018-11-29T11:47:20.000000Z
4     38                   England  ENG     https://cdn.sportmonks.com/images/cricket/teams/6/38.png      190324           True  2019-01-29T11:07:04.000000Z
5     39                 Sri Lanka  LKA     https://cdn.sp

In [137]:
player.loc[0,"code"] = "GHANA"

In [139]:
player.to_csv("teams.csv", index=False)

In [141]:
print(player.to_string())

      id                      name   code                                                   image_path  country_id  national_team                   updated_at
0      1                     Ghana  GHANA      https://cdn.sportmonks.com/images/cricket/teams/1/1.png      190324           True  2018-11-29T11:47:20.000000Z
1     10                     India    IND    https://cdn.sportmonks.com/images/cricket/teams/10/10.png      190324           True  2018-11-29T11:47:20.000000Z
2     36                 Australia    AUS     https://cdn.sportmonks.com/images/cricket/teams/4/36.png      190324           True  2018-11-29T11:47:20.000000Z
3     37                Bangladesh    BGD     https://cdn.sportmonks.com/images/cricket/teams/5/37.png      190324           True  2018-11-29T11:47:20.000000Z
4     38                   England    ENG     https://cdn.sportmonks.com/images/cricket/teams/6/38.png      190324           True  2019-01-29T11:07:04.000000Z
5     39                 Sri Lanka    LKA     